sudo: false

language: java

# Avoid the error: The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during
dist: trusty

jdk: oraclejdk8

services:
  - docker

addons:
  sonarcloud:
    organization: "ressec-github"
    token:
      secure: "${SONAR_TOKEN}"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -f foundation-parent/pom.xml -Dsonar.projectKey=ressec_hemajoo-foundation

deploy:
  provider: script
  script: "cp foundation-parent/etc/deploy-settings.xml $HOME/.m2/settings.xml && mvn deploy -f foundation-parent/pom.xml"
  skip_cleanup: false
  on:
    # Set 'tags' to:
    # . 'true'  which will force the deployment of the artifact after a successful build only when the commit is tagged. So even if a merge request to 'master' is
    #           successful, the built artifact will not be deployed to the repository.
    # . 'false' which will force the deployment of the artifact after a successful build only when merged on the 'master' branch.
    tags: false

notifications:
  email:
    recipients:
      - christophe.resse@gmail.com
    on_success: change
    on_failure: always
