/*
 * (C) Copyright Hemajoo Systems Inc.  2019 - All Rights Reserved
 * -----------------------------------------------------------------------------------------------
 * All information contained herein is, and remains the property of
 * Hemajoo Inc. and its suppliers, if any. The intellectual and technical
 * concepts contained herein are proprietary to Hemajoo Inc. and its
 * suppliers and may be covered by U.S. and Foreign Patents, patents
 * in process, and are protected by trade secret or copyright law.
 *
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained from
 * Hemajoo Systems Inc.
 * -----------------------------------------------------------------------------------------------
 */
package com.ressec.hemajoo.foundation.common.entity.keyable;

import java.lang.annotation.*;

/**
 * Annotation used to annotate one or more fields of a {@link Keyable} entity as alternate keys of this entity.
 * @author <a href="mailto:christophe.resse@gmail.com">Christophe Resse</a>
 * @version 1.0.0
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface AlternateKey
{
    /**
     * The name of the key (must be unique for a keyable entity).
     *
     * @return Key name.
     */
    String name();

    /**
     * Does the key value is mandatory ?
     *
     * @return True if the key value is mandatory, false otherwise.
     */
    boolean mandatory() default true;

    /**
     * Does the key value must be unique ?
     *
     * @return True if the key value must be unique, false otherwise.
     */
    boolean unique() default true;

    /**
     * Does the key value is generated by the key manager ?
     *
     * @return True if the key value is generated by the key manager, false otherwise.
     */
    boolean auto() default false;
}

