/*
 * (C) Copyright Hemajoo Systems Inc.  2019 - All Rights Reserved
 * -----------------------------------------------------------------------------------------------
 * All information contained herein is, and remains the property of
 * Hemajoo Inc. and its suppliers, if any. The intellectual and technical
 * concepts contained herein are proprietary to Hemajoo Inc. and its
 * suppliers and may be covered by U.S. and Foreign Patents, patents
 * in process, and are protected by trade secret or copyright law.
 *
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained from
 * Hemajoo Systems Inc.
 * -----------------------------------------------------------------------------------------------
 */
package com.ressec.hemajoo.foundation.common.entity.keyable;

import java.lang.annotation.*;

/**
 * Annotation used to annotate one field of a {@link IKeyable} entity as the primary key of this entity.
 * A primary key value is unique and is also mandatory except if the property 'auto' is set to true.
 * @author <a href="mailto:christophe.resse@gmail.com">Christophe Resse</a>
 * @version 1.0.0
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface PrimaryKey
{
    /**
     * The name of the key (it must be unique per keyable class).
     * @return Key name.
     */
    String name();

//    /**
//     * Does the key value must be unique ?
//     * @return True if the key value must be unique, false otherwise.
//     */
//    boolean unique() default true;
//
//    /**
//     * Does the key value is mandatory ?
//     * @return True if the key value is mandatory, false otherwise.
//     */
//    boolean mandatory() default true;

    /**
     * Does the key value is generated by the key manager ?
     * @return True if the key value is generated by the key manager, false otherwise.
     */
    boolean auto() default false;

    //public String prefix() default ""; TODO For future implementation

    //public String suffix() default ""; TODO For future implementation

    //public String pattern() default "T145-${KEY_VALUE}-KOL236"; TODO For future implementation

    //public String padding() default "0"; TODO For future implementation
}
